version: '2.4'

services:
  node:
    build:
      dockerfile: 5.Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app:delegated
    ports:
      - "7000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:11.5
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s